name: Deploy ASP.NET CORE

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: SmartFarmbyKarlo
  AZURE_WEBAPP_PATH: '.'
  DOTNET_VERSION: '7.0.200'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: SETUP .NET CORE
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}